export const SERVICE_INTERVALS_SEED = [
  { make: "Lada", models: ["Vesta", "Granta", "Niva", "XRAY", "Largus"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Toyota", models: ["Camry", "RAV4", "Corolla", "Land Cruiser", "Hilux", "Fortuner"], intervalKm: 10000, intervalMonths: 12 },
  { make: "Hyundai", models: ["Solaris", "Tucson", "Creta", "Santa Fe", "Elantra", "i30"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Kia", models: ["Rio", "Sportage", "Ceed", "Sorento", "Optima", "Seltos", "K5"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Volkswagen", models: ["Polo", "Tiguan", "Golf", "Passat", "Touareg", "Jetta", "ID.4"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Skoda", models: ["Octavia", "Rapid", "Kodiaq", "Karoq", "Superb", "Yeti", "Fabia"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Renault", models: ["Duster", "Logan", "Sandero", "Kaptur", "Arkana", "Koleos"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Nissan", models: ["Qashqai", "X-Trail", "Almera", "Juke", "Patrol", "Terrano", "Murano"], intervalKm: 15000, intervalMonths: 12 },
  { make: "BMW", models: ["3 Series", "5 Series", "X3", "X5", "X1", "7 Series", "X6"], intervalKm: 15000, intervalMonths: 24 },
  { make: "Mercedes-Benz", models: ["C-Class", "E-Class", "GLC", "GLE", "S-Class", "A-Class", "GLA"], intervalKm: 15000, intervalMonths: 24 },
  { make: "Audi", models: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8"], intervalKm: 15000, intervalMonths: 24 },
  { make: "Mazda", models: ["3", "6", "CX-5", "CX-9", "CX-30", "MX-5"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Ford", models: ["Focus", "Kuga", "Mondeo", "Explorer", "EcoSport", "Fiesta"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Chevrolet", models: ["Cruze", "Niva", "Aveo", "Cobalt", "Tracker", "Tahoe"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Mitsubishi", models: ["Outlander", "ASX", "Pajero", "L200", "Eclipse Cross", "Lancer"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Honda", models: ["CR-V", "Civic", "Accord", "HR-V", "Pilot", "Jazz"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Subaru", models: ["Forester", "Outback", "XV", "Impreza", "Legacy", "WRX"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Suzuki", models: ["Vitara", "SX4", "Jimny", "Swift", "Grand Vitara"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Geely", models: ["Atlas", "Coolray", "Tugella", "Monjaro", "Emgrand"], intervalKm: 10000, intervalMonths: 12 },
  { make: "Chery", models: ["Tiggo 4", "Tiggo 7 Pro", "Tiggo 8 Pro", "Arrizo", "Omoda"], intervalKm: 10000, intervalMonths: 6 },
  { make: "Haval", models: ["Jolion", "F7", "H9", "Dargo", "H5"], intervalKm: 10000, intervalMonths: 12 },
  { make: "Changan", models: ["CS35 Plus", "CS55 Plus", "CS75 Plus", "Uni-K", "Uni-V"], intervalKm: 10000, intervalMonths: 6 },
  { make: "GAC", models: ["GS8", "GS5", "GN6", "Empow"], intervalKm: 10000, intervalMonths: 6 },
  { make: "Volvo", models: ["XC60", "XC90", "S60", "S90", "V60", "XC40"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Peugeot", models: ["308", "408", "3008", "5008", "2008", "Partner"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Citroen", models: ["C4", "C5", "Berlingo", "C-Elysee", "C3"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Lexus", models: ["RX", "NX", "ES", "LX", "GX", "IS"], intervalKm: 10000, intervalMonths: 12 },
  { make: "Infiniti", models: ["QX50", "QX60", "QX80", "Q50", "Q60"], intervalKm: 15000, intervalMonths: 12 },
  { make: "Land Rover", models: ["Discovery", "Range Rover", "Defender", "Freelander", "Evoque"], intervalKm: 16000, intervalMonths: 12 },
  { make: "Porsche", models: ["Cayenne", "Macan", "Panamera", "911", "Taycan"], intervalKm: 15000, intervalMonths: 24 },
];
